#!/usr/bin/sh

# Add color support
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# cmake
alias cmakebt='ctest -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --build-and-test . build -G Ninja --test-command ctest '
alias cmakej='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja'
alias cmakeiwyu='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja -DCMAKE_C_COMPILER_VERSION=clang-8 -DCMAKE_CXX_COMPILER_VERSION=clang++-8 -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE=iwyu'

# date
alias hours='date +%T'
alias day='date +%A'
alias month='date +%B'
alias year='date +%Y'

alias god-gdb='echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid >/dev/null && echo 0 | sudo tee /proc/sys/kernel/kptr_restrict >/dev/null'

# ls
alias ll='ls -lh'
alias la='ls -A'
alias lla='ls -lAh'

# neofetch
alias neofetch='neofetch --ascii ${XDG_CONFIG_HOME}/neofetch/$(hostname)_image'

# rm
alias rm='rm --preserve-root'

# tree
alias tree='tree --dirsfirst'
