#!/bin/sh

# Add color support
alias ls='ls --color=auto --group-directories-first'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# cmake
alias cmakej="cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja"
alias cmakebt='ctest --timeout 1 --build-and-test . build --build-generator Ninja --test-command ctest --output-on-failure'
alias cmakeqt14and='cmakej -DQt5_DIR=${XDG_LOCAL_HOME}/lib/Qt/5.14.1/android/lib/cmake/Qt5'
alias cmakeqt14gcc='cmakej -DQt5_DIR=${XDG_LOCAL_HOME}/lib/Qt/5.14.1/gcc_64/lib/cmake/Qt5'
alias cmakeqt12gcc='cmakej -DQt5_DIR=${XDG_LOCAL_HOME}/lib/Qt/5.12.3/gcc_64/lib/cmake/Qt5'

# darling
alias darling='env -i HOME=${HOME} DPREFIX=${DPREFIX} TERM=${TERM} PATH=${PATH} darling'

# date
alias hours='date +%T'
alias day='date +%A'
alias month='date +%B'
alias year='date +%Y'

# df
alias space='df -h | head -n 1 && df -h --total --exclude-type tmpfs| tail -n +2 | sort -hrk 2'

alias gdb='gdb --silent'
alias gdba='gdb --args'

alias god-gdb='echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid >/dev/null && echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope >/dev/null && echo 0 | sudo tee /proc/sys/kernel/kptr_restrict >/dev/null'

# ls
alias ll='ls -lh'
alias la='ls -A'
alias lla='ls -lAh'

# neofetch
alias neofetch='neofetch --ascii ${XDG_CONFIG_HOME}/neofetch/$(hostname)_image'

# xdg-open
alias open='xdg-open'

# qjoypad
alias qjoypad='qjoypad --notray'

# rm
alias rm='rm --preserve-root'

# tmux
alias lock='tmux detach'
alias tmux-default-cfg='tmux -Lfoo -f/dev/null start\; show -gw'
alias tmux-current-cfg='tmux -Lfoo -f/dev/null start\; show -g'

# tree
alias tree='tree --dirsfirst'

# watchexec helpers
alias runaout='watchexec --clear --ignore *pp ./a.out'
alias runcmakebt='watchexec --clear --ignore build "ctest --build-and-test . build --build-generator Ninja --test-command ctest --output-on-failure"'
