#!/bin/sh
set -eu

if [ $# -lt 1 ]; then
	echo "No file specified.\nUsage: 7z-compress file"
	exit 1
elif [ $# -gt 1 ]; then
	echo "Too many files specified.\nUsage: 7z-compress file"
	exit 1
fi

if [ ! -f "${1}" ] && [ ! -d "${1}" ]; then
	echo "${1} doesn't exist."
	exit 1
fi

7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on "${1}".7z "${1}"
