#!/bin/sh
set -euf

for arg in "${@:-}"; do
	case "${arg}" in
		--help) printf "Check if the machine can ping Google\n  --repeat  Keep trying over and over\n  --notify  Notify the change (TO BE IMPLEMENTED)\n"; exit;;
	--repeat) REPEAT=true;;
	--notify) NOTIFY=true;;
	esac
done

check()
{
	if [ "$(uname -o)" = "Msys" ]; then
		PING_FLAGS="-n 1 -w 2000"
	else
		PING_FLAGS="-c 1 -W 2"
	fi

	if ping 8.8.8.8 $PING_FLAGS 1>/dev/null; then
		echo yes
		return 0
	else
		echo no
		return 1
	fi
}

if ${REPEAT:-false}; then
	while :; do
		check
		sleep 2
	done;
else
	check || exit 1
fi
