#!/bin/sh
set -euf

if [ "$(uname -o)" = "Msys" ]; then
	if ping 8.8.8.8 -n 1 -w 2000 1>/dev/null; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
else
	if ping 8.8.8.8 -c 1 -W 2 1>/dev/null; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
fi
