#!/bin/sh
if [ -z "${1:-}" ]; then
	echo Please pass at least one parameter.
	exit 1
fi

c++ -c -S -fno-ident -finhibit-size-directive -fno-PIC -fno-rtti -fno-exceptions -fno-asynchronous-unwind-tables -fno-stack-protector -fcf-protection=none -fno-dwarf2-cfi-asm -Wa,-alh,-L -o- $@ | grep -v '.section\|.text\|.globl\|.type\|.file\|.p2align\|.align' | c++filt
