#!/bin/bash

HEX_VALUES="0 1 2 3 4 5 6 7 8 9 a b c d e f"

for HEX_0 in ${HEX_VALUES}
do
	for HEX_1 in ${HEX_VALUES}
	do
		for HEX_2 in ${HEX_VALUES}
		do
			for HEX_3 in ${HEX_VALUES}
			do
				echo -ne "\\u${HEX_3}${HEX_2}${HEX_1}${HEX_0} "
			done
		done
	done
done
echo
