#!/bin/bash

printColoredNumbersRow ()
{
	for color in 0 1 2 3 4 5 6 7
	do
		tput setaf "${color}"
		printf " %s " "${color}"
	done
	echo
}



# Reset dirty edits
tput sgr0

tput dim
printf "Dimmed     "
printColoredNumbersRow

tput sgr0
printf "Normal     "
printColoredNumbersRow

tput bold
printf "Bold       "
printColoredNumbersRow



# Reset dirty edits
tput sgr0

echo
printf "Background "
for color in 0 1 2 3 4 5 6 7
do
	tput setab "${color}"
	printf "   "
done
tput sgr0
echo



# Reset dirty edits
tput sgr0
for i in {0..255}; do
	printf "\x1b[38;5;${i}m%3d " "${i}"
	if (( $i % 12 == 0 )); then
		echo;
	fi
done
echo
