#!/bin/sh
set -euf

MAX_VALUE_0=$(cat /sys/class/power_supply/BAT0/energy_full)
CURRENT_VALUE_0=$(cat /sys/class/power_supply/BAT0/energy_now)
MAX_VALUE_1=$(cat /sys/class/power_supply/BAT1/energy_full)
CURRENT_VALUE_1=$(cat /sys/class/power_supply/BAT1/energy_now)
PERCENTAGE=$((  (CURRENT_VALUE_0 + CURRENT_VALUE_1)  * 100 / (MAX_VALUE_0 + MAX_VALUE_1) ))

echo "$PERCENTAGE"%
